# Do not edit this file, copy this file & rename it to const.py. Any format error will result in not getting start or help message.

from pyrogram.types import InlineKeyboardMarkup, InlineKeyboardButton


#use the same format for name & user_id placeholders
START_MSG = """
Hi **[{}](tg://user?id={})**,𝐈’𝐦 𝐭𝐡𝐞 𝐀𝐍𝐆𝐑𝐘 😡 𝐁𝐈𝐑𝐃 𝐅𝐢𝐥𝐞 𝐒𝐞𝐫𝐯𝐞 𝐁𝐨𝐭 𝐟𝐫𝐨𝐦 𝐓𝐞𝐚𝐦 𝐅𝐢𝐫𝐞⚡𝐁𝐨𝐥𝐭 !  
𝐍𝐞𝐞𝐝 𝐚 𝐌𝐎𝐕𝐈𝐄 𝐨𝐫 𝐒𝐄𝐑𝐈𝐄𝐒 ? 𝐉𝐮𝐬𝐭 𝐬𝐞𝐧𝐝 𝐭𝐡𝐞 𝐧𝐚𝐦𝐞, 𝐚𝐧𝐝 𝐈’𝐥𝐥 𝐟𝐢𝐧𝐝 𝐢𝐭 𝐟𝐨𝐫 𝐲𝐨𝐮 𝐢𝐧𝐬𝐭𝐚𝐧𝐭𝐥𝐲! 🍿🎥

𝐖𝐚𝐧𝐭 𝐭𝐨 𝐤𝐧𝐨𝐰 𝐦𝐨𝐫𝐞? 𝐓𝐲𝐩𝐞 /help 𝐟𝐨𝐫 𝐚𝐥𝐥 𝐜𝐨𝐦𝐦𝐚𝐧𝐝𝐬.  
𝐋𝐞𝐭’𝐬 𝐡𝐮𝐧𝐭 𝐝𝐨𝐰𝐧 𝐬𝐨𝐦𝐞 𝐠𝐫𝐞𝐚𝐭 𝐜𝐨𝐧𝐭𝐞𝐧𝐭!
"""

HELP_MSG = """
**REQUEST FORMAT :-**
*MOVIE NAME WITH YEAR (LANGUAGE OPTIONAL)

**REQUEST LIKE THIS :-**
=>IRON MAN✅
=>IRON MAN 2008✅
=>IRON MAN 2008 TAMIL✅

**DON'T REQUEST LIKE THIS :-**
=>IRON MAN MOVIE ❌
=>IRON MAN 2008 GIVE ❌
=>IRON MAN 2008 ANAPUGA  ❌

[🙅Don't use this words while searching: HD, MOVIES, SEND, PREDVD, WEB-DL, ANAPUGA, SEND PANNUGA, HDrip, VENUM]

**If Any Movies Not Available Send Your MOVIE NAMES To This Bot ✨
AND REPORT HERE IF BOT IS NOT WORKING 👉 @ANGRY_BIRD22_bot**

**You can find the bot commands here.**
**User Commands:-**
/help - __Show this help message__
/settings - __Toggle settings of Precise Mode and Button Mode__
`Precise Mode:` 
- __If Enabled, bot will match the word & return results with only the exact match__
- __If Disabled, bot will match the word & return all the results containing the word__    
`Result Mode:` 
- __If Button, bot will return results in button format__
- __If List, bot will return results in list format__
- __If HyperLink, bot will return results in hyperlink format__

**Admin Commands:-**
/logs - __Get logs as a file__
/server - __Get server stats__
/restart - __Restart the bot__
/stats - __Get bot user stats__
/broadcast - __Reply to a message to send that to all bot users__
/index - __Start indexing a database channel (bot must be admin of the channel if that is provate channel)__
__You can just forward the message from database channel for starting indexing, no need to use the /index command__
/delete - __Reply to a file to delete it from database__
/autodelete - __Set file auto delete time in seconds__
/repairmode - __Enable or disable repair mode - If on, bot will not send any files__
/customcaption - __Set custom caption for files__
/adminsettings - __Get current admin settings__
/ban - __Ban a user from bot__ - `/ban user_id`
/unban - __Unban a user from bot__ - `/unban user_id`
/addfilter - __Add a text filter__ - `/addfilter filter message` __or__ `/addfilter "filter multiple words" message` __(If a filter is there, bot will send the filter rather than file)__
/delfilter - __Delete a text filter__ - `/delfilter filter`
/listfilters - __List all filters currently added in the bot__
/forcesub - __Set force subscribe channel__ - `/forcesub channel_id` __Bot must be admin of that channel (Bot will create a new invite link for that channel)__
/checklink - __Check invite link for force subscribe channel__
/total - __Get count of total files in DB__
"""


START_KB = InlineKeyboardMarkup(
    [
        [
            InlineKeyboardButton("🆘 Help", callback_data="help_cb"),
            InlineKeyboardButton(
                "📞 Contact", url="https://telegram.me/ANGRY_BIRD22_bot"
            )
        ],
        [ 
            InlineKeyboardButton(
                "❓ How To Download ❓", url="https://telegram.me/FIREBOLTTutorial/20"
            )
        ],
    ]
)

HELP_KB = InlineKeyboardMarkup(
    [
        [
            InlineKeyboardButton("🔙 Back", callback_data="back_m"),
        ],
    ]
)
